server:
  port: 8085
spring:
  application:
   name: guestbook
  jpa:
    hibernate:
      ddl-auto: update

---

spring:
  profiles: default
  jpa:
    database: HSQL

---

spring:
  profiles: cloud
  jpa:
    database: POSTGRESQL
